name: RBEconomy
main: com.hanriel.reboot_economy.Eco
version: "21.26.2.0"
load: STARTUP
commands:
  eco:
    description: Работа с балансом пользователя
    usage: /<command> [add|set <currensy> <amount>]
    aliases: [b, bal, balance, money, и, ифд, ифдфтсу, ьщтун]
  pay:
    description: Совершить перевод денег другому игроку
    usage: /<command> <player> <amount(В меди)>
    aliases: [зфн]