name: RBCore
main: com.hanriel.reboot_core.Core
version: "20.20.4.5"
load: POSTWORLD
commands:
  core:
    description: ReBoot core info.
    usage: /<command> [help [admin],reload]
    aliases: [сщку]